### ISSUE TITLE
What hardware are you using?

### ISSUE THREAD

**Issue by samuk** [Alexander-Levy/mower_bot#1]
Hi your project looks interesting. I'd like to make a mower too.

My current plan was to start from https://github.com/linorobot/linorobot2 as a bunch of work is done there and there's a community.

Could you say a bit about your hardware? Do you have a MCU between your pi and motor controller? Is that running MicroROS?

I'm just wondering how hard it would be to get your coverage / path planning stuff working under Linorobot?

**Comment by Alexander-Levy** [comment]
Hi samuk! 

I just checked out the package you referenced, seems like a great resource! that sure would have saved me a lot of time with this project haha. 

Regarding your question, i plan to update the read me in the next few days to include the electronic design, pics, videos but for now. 

The robot is differential drive with 2 powered wheels (1 on each side) and a caster wheels in front. The wheels are powered by 12V dc motors with included encoders. There is indeed a micro-controller between the raspberry pi and the motor driver, in my case i am using an Arduino Nano. 

The micro-controller is not running micro-Ros, instead it is running the [ros_arduino_bridge firmware](https://github.com/joshnewans/ros_arduino_bridge). Its basically an arduino program that tells the board(the nano) how to set up its pins(listen for encoder pulses, outputs pwm values to motor driver (L298N in my case)) and also sets up communication over serial. Its important to realize that it blindly listens to the commands that its giving and executes them, this includes things such as setting the motor to a defined speed and sending back encoder info. This servers as the hardware that our hardware interface will be talking to from the ros side. 

On the ROS side control is being done with ros2 control (feel free to look at the ros2_control.xacro). I am running the [diffdrive_arduino package](https://github.com/joshnewans/diffdrive_arduino.git) mentioned in the dependencies. It basically interfaces the hardware with the rest of Ros. So how it works is more or less something like this.
1. Some ROS2 node published a command velocity to the controller.
2. The differential drive controller reads the input and sends a command to the hardware.
3. The hardware(Arduino) converts the input speed to pwm value for the motors.
4. The hardware sends encoder values to the controller
5.  Controller calculates odometry and velocity based on feedback.

Credit to @joshnewans for both packages. Check out his execelent videos on motor controls, ros2 control and hardware interfaces to learn more on the matter.  

My implementation is based on this and modified a bit to add control to the mower motor itself. I could post that code as well i guess but it is extremely similar to this one, so i would just use that one as a base and work from there.

For obstacle detection, i used the rplidar a1m8, its pretty much the go-to in terms of cheap lidars, worked great for me. 

If you need any more info on the hardware let me know, so that i may also include it in my next commit and maybe add the concept to the read-me.

Regarding the coverage / path planning, im doing that on this [repo](https://github.com/Alexander-Levy/coverage_navigator) but as you can see its still early stages and really only ready for demo use. However it should work as long as you have some map (either loaded from a saved file or created on the spot) and the navigation stack.

**Comment by samuk** [comment]
Thanks, I meant to reply more fully but life became busy. Once your path planning is more mature I might have a go at getting that running under the linorobot code base I mentioned.
